insert into affiliation(name, phone, street, city, state, zipcode) values('Center For Disease Control And Prevention', '404-639-3286', '1600 Clifton Rd', 'Atlanta', 'Georgia', '30333');
insert into affiliation(name, phone, street, city, state, zipcode) values('National Institute of Mental Health', '301-496-5787', '9000 Rockville Pike', 'Bethesda', 'Maryland', '20982');
insert into affiliation(name, phone, street, city, state, zipcode) values('Mercer County Planning Division', '609-278-7137', '640 South Broad St', 'Trenton', 'New Jersey', '08650');
insert into affiliation(name, phone, street, city, state, zipcode) values('Environmental Sanitation Division', '215-345-3333', '55 East Court Street', 'Doylestown', 'Pennsylvania', '18901');
insert into affiliation(name, phone, street, city, state, zipcode) values('Environmental Services of Burlington County', '609-265-5515', '15 Pioneer Blvd', 'Westhampton', 'New jersey', '08060');
insert into affiliation(name, phone, street, city, state, zipcode) values('Middlesex County Public Health Department', '732-745-3123', '75 Bayard St 5th Floor', 'New Brunswick', 'New Jersey', '08901');
insert into affiliation(name, phone, street, city, state, zipcode) values('TCNJ', '609-771-2131', '2000 Pennington Rd', 'Ewing', 'New Jersey', '08618');
insert into affiliation(name, phone, street, city, state, zipcode) values('Rutgers', '732-445-4636', '83 Somerset St', 'New Brunswick', 'New Jersey', '08901');
insert into affiliation(name, phone, street, city, state, zipcode) values('Thomas Edison State College', '888-442-8372', '101 W State St', 'Trenton', 'New Jersey', '08608');
insert into affiliation(name, phone, street, city, state, zipcode) values('National Center For Neighborhood And Brownfields Redevelopment', '848-932-2714', '33 Livingston Ave', 'New Brunswick', 'New Jersey', '08901');
insert into affiliation(name, phone, street, city, state, zipcode) values('NJDEP', '609-777-3373', '401 East State St', 'Trenton', 'New Jersey', '08608');
insert into affiliation(name, phone, street, city, state, zipcode) values('Ewing Township City Council', '609-883-7695', '2 Jake Garzio Drive', 'Ewing', 'New Jersey', '08618');
insert into affiliation(name, phone, street, city, state, zipcode) values('The City Of Trenton Division Of Health', '609-989-3242', '19 East State St', 'Trenton', 'New Jersey', '08608');
insert into affiliation(name, phone, street, city, state, zipcode) values('Clean Water Action', '732-963-9714', '198 Brighton Ave', 'Long Branch', 'New Jersey', '07740');
insert into affiliation(name, phone, street, city, state, zipcode) values('Delaware Riverkeeper Network', '215-369-1188', '925 Canal Street', 'Bristol', 'Pennsylvania', '19007');
insert into affiliation(name, phone, street, city, state, zipcode) values('Star Ledger', '732-560-1560', '20 Duke Rd', 'Piscataway', 'New Jersey', '08854');
insert into affiliation(name, phone, street, city, state, zipcode) values('Statehouse News Bureau', '614-221-1811', 'Room 015 The Statehouse', 'Columbus', 'Ohio', '43215');
insert into affiliation(name, phone, street, city, state, zipcode) values('Environmental Research Foundation', '732-828-9995', 'P.O. Box 160', 'New Brunswick', 'New Jersey', '08908');
insert into affiliation(name, phone, street, city, state, zipcode) values('Geosyntec Consultants', '609-895-1400', '7 Graphics Dr', 'Ewing', 'New Jersey', '08628');
insert into affiliation(name, phone, street, city, state, zipcode) values('CSG Environmental Consultants, Inc.', '609-393-4442', '109 Renfrew Ave', 'Trenton', 'New Jersey', '08618');
insert into affiliation(name, phone, street, city, state, zipcode) values('Sovereign Consulting, Inc.', '609-259-8200', '111A N Gold Dr', 'Trenton', 'New Jersey', '08691');
insert into affiliation(name, phone, street, city, state, zipcode) values('USA Environmental Management', '609-656-8101', '344 West State St', 'Trenton', 'New Jersey', '08618');
