insert into expert(area_of_expertice, title) values('Public Health', 'Director');
insert into expert(area_of_expertice, title) values('Public Health', 'Associate Director For Communications And Public Liason');
insert into expert(area_of_expertice, title) values('Public Health', 'Media Contact');
insert into expert(area_of_expertice, title) values('Public Health', 'Bureau Director');
insert into expert(area_of_expertice, title) values('Environmental Sociology', 'Sociology Professor');
insert into expert(area_of_expertice, title) values('Green Chemistry', 'Chemistry Professor');
insert into expert(area_of_expertice, title) values('Biodegradable Materials', 'Chemistry Professor');
insert into expert(area_of_expertice, title) values('Environmental History', 'History Professor');
insert into expert(area_of_expertice, title) values('Pine Barrens Birds', 'Biology Professor');
insert into expert(area_of_expertice, title) values('Public Health', 'Sociology Professor');
insert into expert(area_of_expertice, title) values('Epidemiology', 'Sociology Professor');
insert into expert(area_of_expertice, title) values('Human Toxic Chemicals', 'Mathematics Professor');
insert into expert(area_of_expertice, title) values('Organic Contaminants', 'Chemistry Professor');
insert into expert(area_of_expertice, title) values('Biological Waste Treatment', 'Environmental Science Professor');
insert into expert(area_of_expertice, title) values('Environmental Justice', 'Director');
insert into expert(area_of_expertice, title) values('Solid Waste And Pesticide Enforcement', 'Director');
insert into expert(area_of_expertice, title) values('Solid Waste And Pesticide Enforcement', 'Administrative Support');
insert into expert(area_of_expertice, title) values('Solid Waste And Pesticide Enforcement', 'Supervisor');
insert into expert(area_of_expertice, title) values('Solid Waste And Pesticide Enforcement', 'Supervisor');
insert into expert(area_of_expertice, title) values('Solid Waste And Pesticide Enforcement', 'Supervisor');
insert into expert(area_of_expertice, title) values('Solid Waste And Pesticide Enforcement', 'Supervisor');
insert into expert(area_of_expertice, title) values('Licensing And Pesticide Operations', 'Support Staff');
insert into expert(area_of_expertice, title) values('Licensing And Pesticide Operations', 'Supervisor');
insert into expert(area_of_expertice, title) values('Water Waste And Licensing', 'Supervisor');
insert into expert(area_of_expertice, title) values('Water And Land Use Enforcement', 'Director');
insert into expert(area_of_expertice, title) values('Water And Land Use Enforcement', 'Bureau Chief');
insert into expert(area_of_expertice, title) values('Water And Land Use Enforcement', 'Supervisor');
insert into expert(area_of_expertice, title) values('Air And Hazardous Materials Enforcement', 'Operations Assistant');
insert into expert(area_of_expertice, title) values('Local Environmental Management', 'Support Staff');
insert into expert(area_of_expertice, title) values('Air Compliance And Enforcement', 'Supervisor');
insert into expert(area_of_expertice, title) values('Diesel Enforcement', 'Supervisor');
insert into expert(area_of_expertice, title) values('Air Compliance And Enforcement', 'Bureau Chief');
insert into expert(area_of_expertice, title) values('Public Health', 'Health Officer');
insert into expert(area_of_expertice, title) values('Environmental Protection', 'Commissioner');
insert into expert(area_of_expertice, title) values('Public Health', 'Principal Sanitary Inspector');
insert into expert(area_of_expertice, title) values('Public Health', 'Health Officer');
insert into expert(area_of_expertice, title) values('Clean Water', 'Director');
insert into expert(area_of_expertice, title) values('Environmental Justice', 'Protestor');
insert into expert(area_of_expertice, title) values('Hurricane Sandy', 'Journalist');
insert into expert(area_of_expertice, title) values('Nonprofits', 'Journalist');
insert into expert(area_of_expertice, title) values('Politics', 'Journalist');
insert into expert(area_of_expertice, title) values('Environmental Justice', 'Journalist');
insert into expert(area_of_expertice, title) values('Energy', 'Journalist');
insert into expert(area_of_expertice, title) values('Environmental Standards', 'Journalist');
insert into expert(area_of_expertice, title) values('Politics', 'Journalist');
insert into expert(area_of_expertice, title) values('Hurricane Sandy', 'Journalist');
insert into expert(area_of_expertice, title) values('Port Authority', 'Journalist');
insert into expert(area_of_expertice, title) values('Politics', 'Journalist');
insert into expert(area_of_expertice, title) values('Environmental Justice', 'Journalist');
insert into expert(area_of_expertice, title) values('Environmental and Land Use', 'Legal Expert');
insert into expert(area_of_expertice, title) values('Environmental and Land Use', 'Legal Expert');
insert into expert(area_of_expertice, title) values('Plant Health and Forestry', 'Legal Expert');
insert into expert(area_of_expertice, title) values('Environment', 'Legal Expert');
insert into expert(area_of_expertice, title) values('Environment', 'Legal Expert');
insert into expert(area_of_expertice, title) values('Environment', 'Legal Expert');
insert into expert(area_of_expertice, title) values('Environment', 'Legal Expert');
insert into expert(area_of_expertice, title) values('Environment', 'Legal Expert');
insert into expert(area_of_expertice, title) values('Environment', 'Legal Expert');
insert into expert(area_of_expertice, title) values('Environment', 'Legal Expert');
insert into expert(area_of_expertice, title) values('Plant Health and Forestry', 'Legal Expert');
